
##
## Config.pm
##
## Configuration for cactusinterfacing.
## Setups some variables, change for your needs.
##

package Cactusinterfacing::Config;

use strict;
use warnings;
use Exporter 'import';

# export
our @EXPORT_OK = qw($debug $verbose $tab $astyle_options);

# debug
our $debug   = 1;
our $verbose = 1;

# coding style
# used for indention of auto generated code
our $tab = "\t";

# Some of the autogenerated code may not fit into a specific coding style per
# default. This is why `astyle' will be used to reformat the code. The following
# variable specifies the options passed to `astyle'. This default options adapt
# the LibGeoDecomp's coding style. Change to whatever you want. If `astyle' is
# not found on the system, the code will be left untouched.
our $astyle_options = "--indent=spaces=4 --brackets=linux --indent-labels ".
	                  "--pad-oper --unpad-paren --pad-header ".
	                  "--keep-one-line-statements --suffix=none ".
	                  "--convert-tabs --indent-preprocessor";

1;
